name: transit_dart

description: >-
  This library provides support for marshalling Transit data to/from Dart.

version: 0.8.90   #--TRANSIT_DART_VERSION--

environment:
  sdk: '>=3.0.0 <4.0.0'

repository: https://github.com/wevre/transit-dart

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

dependencies:
  collection: ^1.17.0
  typed_data: ^1.3.1
