#!/bin/sh

# This setup assumes a sibling folder `transit-test` with inside it two folders,
# one for `transit-format` and another `transit-dart`. It's just for quick
# testing while working on transit-dart locally on my machine, where I have
# exactly the setup described above. The actual roundtrip test should be
# conducted from `transit-format` and will pull down a clone of the latest
# transit-dart.

cd `dirname $0`/..

cp test/roundtrip.dart ../transit-test/transit-dart/test/roundtrip.dart

../transit-test/transit-format/bin/verify -impls dart
